// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDgb_SGJKIxRl8kX9Jzq_gNp_qRsPxulU',
    appId: '1:435724410112:web:07202943cb35034c2ba7e5',
    messagingSenderId: '435724410112',
    projectId: 'gerryapp',
    authDomain: 'gerryapp.firebaseapp.com',
    databaseURL: 'https://gerryapp-default-rtdb.firebaseio.com',
    storageBucket: 'gerryapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdjNeTsNI5J6hND3lhy-Np9QBPv5SXWbg',
    appId: '1:435724410112:android:9f1b90dc286378182ba7e5',
    messagingSenderId: '435724410112',
    projectId: 'gerryapp',
    databaseURL: 'https://gerryapp-default-rtdb.firebaseio.com',
    storageBucket: 'gerryapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB09IQoEUqSSzKRlhX5yn0OsU9ocn4bz_A',
    appId: '1:435724410112:ios:a2d50a5b9804fee22ba7e5',
    messagingSenderId: '435724410112',
    projectId: 'gerryapp',
    databaseURL: 'https://gerryapp-default-rtdb.firebaseio.com',
    storageBucket: 'gerryapp.firebasestorage.app',
    iosBundleId: 'com.example.holaGerry',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB09IQoEUqSSzKRlhX5yn0OsU9ocn4bz_A',
    appId: '1:435724410112:ios:a2d50a5b9804fee22ba7e5',
    messagingSenderId: '435724410112',
    projectId: 'gerryapp',
    databaseURL: 'https://gerryapp-default-rtdb.firebaseio.com',
    storageBucket: 'gerryapp.firebasestorage.app',
    iosBundleId: 'com.example.holaGerry',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDgb_SGJKIxRl8kX9Jzq_gNp_qRsPxulU',
    appId: '1:435724410112:web:4ab4c01c155e69cf2ba7e5',
    messagingSenderId: '435724410112',
    projectId: 'gerryapp',
    authDomain: 'gerryapp.firebaseapp.com',
    databaseURL: 'https://gerryapp-default-rtdb.firebaseio.com',
    storageBucket: 'gerryapp.firebasestorage.app',
  );
}
